(function () {
    'use strict';

    //hämtar Application-modulen som redan är skapad i Application.js
    var application = angular.module('App');

    //Binder direktivet till vår modul
    application.directive('courses', [function () {

        function link($scope, $element, $attrs) {
          
            $scope.oneAtATime = true;
            $scope.fields = ['name', 'id', 'hp'];
            $scope.courses = [

            {   hp: 6,
                type: 1,
                id: "TEIE84",
                name: "Industriell ekonomi fk.",
                desc: "Med utgångspunkten från kunskaperna från TEIE53, där ett företagens ekonomi undersöks och analyseras, handlar TEIE84 om att skapa en förståelse för organisationers arbete med att arbeta med strategier och affärmodeller. Utgångspunkten ligger i att förstå processer kring strategier, olika strategiska inriktningar och att analysera företag med hjälp av strategiska analysmodeller." },
            {   hp: 6,
                type: 1,
                id: "TEIE53",
                name: "Industriell ekonomi",
                desc: "Kursen avser att ge de studerande en orientering i de sammanhang företag verkar. Efter kursen ska deltagarna kunna: 1. Beskriva och förklara den verksamhet ett företag bedriver, hur marknaden fungerar, branschtillhörighet och vilka konkurrensstrategier som kan användas. 2. Beskriva, förklara, tillämpa enklare produkt- och investeringskalkyler. 3. Beskriva och förklara bokföringens grundläggande principer. 4. Förklara och analysera årsredovisningar samt beräkna nyckeltal för att analysera räkenskaperna. 5. Beskriva och analysera ett företags ekonomiska och marknadsmässiga position. 6. Kommunicera företagsekonomisk information och relaterade analyser." },
            {   hp: 6,
                type: 1,
                id: "TEIE83",
                name: "Cost Benefitanalys - samhällsekonomisk projektutvärdering",
                desc: "Kursen behandlar grundläggande nationalekonomiskt tänkande, den samhällsekonomiska lönsamhetskalkylens grunder i välfärdsekonomisk teori, hur man går tillväga när man gör en samhällsekonomisk lönsamhetskalkyl, samt metoder att värdera effekter som saknar marknadspris." },
            {   hp: 6,
                type: 1,
                id: "TETS21",
                name: "Företagets logistik",
                desc: "Kursen ger kunskap om ett företags logistiksystem, dvs materialflöden från råvara, via förädling, till slutkund samt därtill hörande informationsflöden. Kunskap ges om ekonomiska begrepp, grundläggande logistikbegrepp, om det operativa logistikarbete som bedrivs inom olika funktioner i materialflödet, om styrning av logistikaktiviteter samt om hur utformningen av logistiksystemet påverkar ett företags ekonomiska resultat. Tyngdpunkten ligger på det producerande företaget." },
            {   hp: 6,
                type: 1,
                id: "TGTU37",
                name: "Teknikens utveckling i samhällsperspektiv",
                desc: "Kursens målsättning är att ge grundläggande kunskaper till studiet av teknik och teknikens utveckling med utgångspunkt i sociala, historiska och kulturella perspektiv samt ge möjlighet att reflektera över relationen teknikutvecklare och teknikbrukare utifrån dessa perspektiv." },
            {   hp: 6,
                type: 1,
                id: "THEN20",
                name: "Engelska",
                desc:"Kursen skall ge träning i att använda det engelska språket på ett korrekt sätt i professionella kontexter. Kursen skall också ge studenterna möjlighet att fördjupa och expandera sitt ordförråd, speciellt med de termer som de kan förväntas träffa på yrkeslivet"},
            {   hp: 6,
                type: 1,
                id: "TNA003",
                name: "Analys I",
                desc: "Student skall tillägna sig den förtrogenhet med matematiska begrepp, resonemang och samband som ryms inom envariabelsanalys samt den färdighet i kalkyl och problemlösning som behövs för de fortsatta studierna" },
            {   hp: 6,
                type: 1,
                id: "TNA004",
                name: "Analys II",
                desc: "Student skall tillägna sig den förtrogenhet med matematiska begrepp, resonemang och samband som ryms inom envariabelsanalys samt den färdighet i kalkyl och problemlösning som behövs för de fortsatta studierna" },
            {   hp: 6,
                type: 1,
                id: "TNA005",
                name: "Tillämpad matematik i teknik och naturvetenskap",
                desc: "Kursen avser att utgöra en brygga mellan de grundläggande matematikkurserna och kurser inom teknik och naturvetenskap. Genom att använda beräkningshjälpmedel som Matlab kan mer realistiska problem studeras och studenterna skall vänja sig vid att naturligt använda det språk som matematikstudierna ger dem för att tala om tillämpade problemställningar." },
            {   hp: 6,
                type: 1,
                id: "TNA006",
                name: "Analys III",
                desc: "Kursen bygger på kursen i Analys I-II. Följaktligen är målen likartade: att ge de studerande förståelse för matematiska begrepp och förtrogenhet med matematiska metoder för funktioner av flera variabler som uppstår i alla grenar av fysik och teknik" },
            {   hp: 6,
                type: 2,
                id: "TND005",
                name: "Programmering fk.",
                desc: "Kursen bygger vidare på TND012 Programmering grk och introducerar särskilt objektorienterad programmering i C++. Huvuddelen av kursen består av ett programmeringsprojekt som ska genomföras i en grupp om 3-4 personer" },
            {   hp: 6,
                type: 2,
                id: "TNE043",
                name: "Mekanik och vågfysik", desc: "Kursen skall ge grundläggande kunskaper inom några centrala delar av den klassiska fysiken samt kännedom om viktiga tillämpningar. Laborationsdelen skall ge erfarenhet av att planera,utföra och redovisa experiment." },
            {   hp: 6,
                type: 2,
                id: "TNG006",
                name: "Matematisk statistik",
                desc: "Kursen avser att lära den studerande förstå och utnyttja grundläggande sannolikhetslära och statistik, dvs teorin för försök som påverkas av slumpmässiga faktorer. Kursen inriktas speciellt på sådana grundläggande kunskaper som krävs för tillämpningar inom teknik, ekonomi och naturvetenskap." },
            {   hp: 6,
                id: "TNG015",
                type: 2,
                name: "Signaler och system",
                desc: "Efter avslutad kurs ska studenten kunna: förklara sambandet mellan tidskontinuerliga och tidsdiskreta signaler, förklara sambandet mellan tidskontinuerliga och tidsdiskreta signaler, förklara skillnaden mellan tids- och frekvensbeskrivingar av signalertillämpa Fourier-, Laplace- och Z-transformen för beräkningar, designa digitala filter för signalbehandling, redogöra för grunderna i adaptiv signalbehandling, skriva en vetenskaplig rapport med ett akademiskt språk." },
            {   hp: 6,
                id: "TNG018",
                type: 2,
                name: "Grunder i logistik och lönsamhetsanalys",
                desc: "Kursen ger kunskap om ett företags logistiksystem, dvs. materialflöden från råvara, via förädling, till slutkund samt därtill hörande informationsflöden. Grundläggande kunskap erhålls om logistikbegrepp samt om samband mellan utformningen av logistik­systemet och företagets ekonomiska resultat. Kursen ger även kunskap om hur man kan beskriva, analysera och förändra ett logistiksystem, i syfte att höja dess effektivitet, samt om strukturerad arbetsmetodik för att bedriva sådana utredningar. Fokus ligger på det enskilda varuproducerande företaget, med en tydlig företags­ekonomisk koppling." },
            {   hp: 6,
                id: "TNG022",
                type: 2,
                name: "Modellbygge och simulering",
                desc: "Kursen skall ge kunskaper om metoder och principer att bygga matematiska modeller för dynamiska system (dvs system som beskrivs med hjälp av differential och/eller differensekvationer). Kursen skall också ge kunskaper om hur modellernas egenskaper studeras genom simulering." },
            {   hp: 6,
                id: "TNG028",
                type: 2,
                name: "Reglerteknik",
                desc: "Kursen skall ge förståelse för dynamiska system och kunskaper om grundläggande metoder för att analysera och dimensionera återkopplade reglersystem." },
            {   hp: 6,
                id: "TNG032",
                type: 2,
                name: "Tillämpad transformteori",
                desc: "Kursen skall ge de matematiska grunderna för de transformmetoder som används i kretsteori, reglerteori, signaler och system, bildbehandling och produktionsekonomi. " },
            {   hp: 2,
                id: "TNG041",
                type: 2,
                name: "Vetenskaplig metodik, källkritik och rapportskrivning",
                desc: "Efter avslutad kurs ska studenten kunna: redogöra för de huvudsakliga begreppen och arbetsmetoderna för vetenskapligt arbete, ha kunskap om kvalitativ och kvantitativ metodkunna kritisera vetenskapliga arbeten, kunna söka och kritiskt granska informationskällor" },
            {   hp: 6,
                id: "TNIU66",
                type: 2,
                name: "Statistik och sannolikhetslära",
                desc: "Kursens mål är att ge en introduktion till matematisk modellering av slumpmässiga försök och till statistiska metoder och begrepp. Den skall även visa på tillämpningar relevanta för de program för vilken den ges." },
            {   hp: 6,
                type: 2,
                id: "TNIU75",
                name: "Linjär algebra",
                desc: "Studenten skall efter genomgången kurs kunna: lösa system av linjära ekvationer samt kunna tolka dessa geometriskt, hantera grundläggande geometriska objekt i två och tre dimensioner (såsom punkter, linjer, plan, vektorer) så att väsentliga relationer mellan dessa objekt kan fångas upp och analyseras, bemästra matrisbegreppet och matriskalkyl så att enkla matrisoperationer (såsom matristransponat, matrisprodukt) kan utföras, förstå och tillämpa basbegreppet samt kunna utföra basbyte, redogöra för och räkna med grundläggande idéer och metoder av teorin av linjära avbildningar inklusive avbildningens invers, egenvärden och egenvektorer, diagonalisering (spektralsatsen) och dimensionssatsen samt relatera dessa till metoder och begrepp i p. 2, 3 och 4." },
            {   hp: 6,
                type: 2,
                id: "TNK046",
                name: "Geografiska informationssystem",
                desc: "Det övergripande syftet med kursen är att ge grundläggande kunskaper om geografiska databaser och ingenjörsverktyget GIS. Dessutom ges en introduktion till generell databasteknik. Efter kursen skall studenten: förstå relationsmodellen och frågespråket SQL, känna till grunderna inom geografisk informationsteknik, känna till ett flertal analysmetoder inom GIS, kunna välja och tillämpa rätt analymetod för olika problemtyper, kunna arbeta självständigt med GIS-programvara och kunna redovisa resultat av GIS-analyser i en tydlig och väl strukturerad rapport" },
            {   hp: 6,
                type: 3,
                id: "TNK047",
                name: "Optimering och systemanalys",
                desc: "Kursen ska ge vidare insikt i modellering och optimering och av beslutsproblem. Modellerna som behandlas rör beslutsanalys. Modeller och metoder för både kontinuerliga och diskreta optimeringsproblem används, diskreta optimeringsmodeller och metoder för att lösa sådana behandlas. Anpassning av standardiserade lösningsmetoder för dessa problemtyper diskuteras och tillämpas. Kursdeltagarna skall efter avslutad kurs kunna formulera och lösa modeller inom beslutsanalys" },
            {   hp: 6,
                type: 3,
                id: "TNK049",
                name: "Optimeringslära",
                desc: "Kursen skall ge kunskaper i optimeringslära, och speciellt optimering av linjära och icke-linjära (kontinuerliga) problem, samt problem med nätverksstruktur." },
            {   hp: 6,
                type: 3,
                id: "TNK061",
                name: "Trafikens infrastruktur",
                desc: "Kursen syftar till att ge grundläggande kunskaper om trafiksystemets infrastruktur, dess uppbyggnad och funktioner, samt om planering av infrastrukturen. Fokus ligger på vägtrafik samt persontransporter." },
            {   hp: 6,
                type: 3,
                id: "TNK067",
                name: "Människa-system-interaktion",
                desc: "Kursen ger en orientering om faktorer som är relevanta vid planering, implementering och utvärdering av tekniska system med människan i centrum." },
            {   hp: 6,
                type: 3,
                id: "TNK089",
                name: "Diskret simulering",
                desc: "Kursen syftar till att ge grundläggande kunskaper i diskret simulering och insikt i hur det kan användas för att analysera system inom bl a kommunikations- och transportområdet. Inom kursen ges också möjlighet att träna praktisk modellering. " },
            {   hp: 6,
                type: 3,
                id: "TNK108",
                name: "Datornät",
                desc: "Målet med kursen är att deltagarna efter avslutad kurs ska kunna: Identifiera de komponenter som bygger upp Internet, Beskriva principen för klient-server- och peer-to-peer-kommunikation, Redogöra för skillnader i egenskaper för olika funktioner och protokoll som används på Internet, Jämföra och förklara användningsområden för olika typer av protokoll, Härleda beteckningar, komponenter, tekniker och funktioner till rätt nivå i TCP/IP-modellen, Beskriva nätverkslagrets funktion och implementering i TCP/IP, Beskriva bakomliggande funktioner och befintliga tekniker för att åstadkomma IT-säkerhet. Förklara möjligheter och begränsningar för realtidskommunikation via Internet, Implementera enklare kommunikationslösningar, Kvantitativt modellera utvalda funktioner i ett TCP/IP-nät, Definiera och beräkna de viktigaste prestandamåtten i paketförmedlade nät, Förklara principerna för fleranvändarsystem" },
            {   hp: 6,
                type: 3,
                id: "TNK113",
                name: "Transportekonomi",
                desc: "Kursen syftar till att belysa betydelsen av transportkostnader och andra ekonomiska förutsättningar för transportsystemets funktion, samt att tydliggöra transportsystemets betydelse för övriga samhället." },
            {   hp: 6,
                type: 3,
                id: "TNKA08",
                name: "Retorik",
                desc: "Kursen är lämplig på de flesta utbildningar, där man har muntliga redovisningar, eller en yrkesroll, som kräver medvetenhet om retorikens grunder, presentationsteknik, bemötande, kroppspråk m m." },
            {   hp: 12,
                type: 3,
                id: "TNSL01",
                name: "Matematik",
                desc: "Kursen syftar till att ge dig som student en positiv start på din utbildning och lägga en stabil grund för kommande matematikkurser på programmet, både vad gäller studieteknik och ämnesinnehåll. Målet är att dina matematikkunskaper skall befästas och stärkas, de matematiska begrepp, resonemang och samband som ligger inom kursen, skall sedan ligga till grund för dina fortsatta studier på programmet. " },
            {   hp: 6,
                type: 3,
                id: "TNSL02",
                name: "Samhällsplanering",
                desc: "Kursen syftar till att ge grundläggande kunskaper om samhällsplanering. Efter fullgjord kurs ska studenten vara orienterad i: samhällsbyggandets historiska utveckling, de lagar som styr samhällsplaneringen, fysiska planer såsom regionplan, översiktsplan och detaljplan, väg- och järnvägsplanering, de underlag som ligger till grund för planeringen planeringsprocessen med samråd och miljöbeskrivningar" },
            {   hp: 6,
                type: 3,
                id: "TNSL03",
                name: "Projekt inom logistik",
                desc: "Kursens målsättning är att introducera studenterna till området logistik, till högskolestudier i Norrköping och till projektarbete." },
            {   hp: 6,
                type: 3,
                id: "TNSL04",
                name: "IT - gk",
                desc: "Denna kurs ger grundläggande kunskaper om hur man konstruerar program i ett högnivåspråk och om hur man skapar och använder kalkylblad. Kursen ger också en introduktion till databasteknik med särskild tonvikt på frågespråket SQL, och om hur man konstruerar dynamiska webbapplikationer" },
            {   hp: 6,
                type: 3,
                id: "TNA002",
                name: "Linjär algebra",
                desc: "Att ge sammanhållen begreppsram för geometrisk och algebraisk teknik med tillämpningar inom analys, datorgrafik, elektroteknik, reglerteknik, linjär optimering m fl. ämnen. Vidare ingår att utveckla förmågan att använda det matematiska språket, skriftligt och muntligt."},
            {   hp: 6,
                type: 3,
                id: "TNK101",
                name: "Trafikteknik och trafikstyrning",
                desc: "Kursens övergripande mål är att ge grundläggande teoretisk och praktisk kunskap om dynamiska trafikmodeller och deras tillämpningar."},
            {   hp: 6,
                type: 3,
                id: "TNA001",
                name: "Matematisk grundkurs",
                desc: "Kursen syftar till att bidra till en positiv start på universitetsstudierna, både då det gäller en social tillhörighet samt att få en repetition av matematik från tidigare studier. Dessutom skall några matematiska begrepp, som för många är nya, introduceras. Ett viktigt mål är att systematiskt ge utvecklingsmöjligheter inom vissa områden genom att använda varierat arbetssätt och flera examinationsmoment. Detta skall bl.a. bidra till att förbättra den studerandes förmåga att reflektera över det egna lärandet och ge förtrogenhet med att arbeta i en grupp, som skall ses som en resurs där goda samarbetsformer uppmuntras."},
            {   hp: 6,
                type: 3,
                id: "TNK080",
                name: "Trådlösa kommunikationssystem",
                desc: "Kursen syftar till att ge kunskap om trådlös kommunikation. Detta geenom förståelse för design, konstruktion och utveckling av trådlösa system med radiokommunikation"},
            {   hp: 6,
                type: 3,
                id: "TNK096",
                name: "Trafikprognoser",
                desc: "Kursen skall ge kunskaper om prognosmodeller för trafik och transportproblem. Kursen ska ge kunskap om hur modellerna kan användas för att göra nulägesanalys, prognos och känslighetsanalys."},
            {   hp: 6,
                type: 3,
                id: "TNK095",
                name: "Planering och simulering av trafik",
                desc: "Kursen har till syfte att ge grundläggande kunskaper rörande planering och simulering av trafiksystem. Kursen ska ge en orientering om olika problemställningar och tillämpningar inom trafikplaneringsområdet, och ge en insikt i hur trafikmodeller kan utnyttjas för analys av trafiksystem med syfte att göra systemet effektivare, säkrare och miljövänligare. Dessutom ska kursen ge en inblick i de bakomliggande teorier på vilka trafikmodellerna är baserade."},
            {   hp: 6,
                type: 1,
                id: "TNK087",
                name: "Datakommunikation och Internet",
                desc: "Syftet med kursen är att ge fördjupade kunskaper inom datakommunikation med fokus på IP protokollet, IP routing, datalänklagret, samt kommunikationsprotokoll för trådlösa och mobila nätverk. Kursen syftar även till att ge deltagarna praktiska färdigheter inom nätverksuppbyggnad. Allt större del av datakommunikationen idag går via Internet och nya tillämpningar utvecklas kontinuerligt. Denna kurs beskriver hur kommunikationen på Internet fungerar och hur Internet kan utnyttjas för att skapa skräddarsydda kommunikationslösningar. Kursen fokuserar på tekniker och protokoll i TCP/IP-modellens datalänk- och nätverkslager. "},
            {   hp: 6,
                type: 1,
                id: "TDDC28",
                name: "Tillämpningar av diskret simulering",
                desc: "Kursens grundidé är att tillämpa i verkligheten och fördjupa sig i de grundläggande kunskaperna i diskret simulering genom att arbeta i grupp med praktiska fall"},
            {   hp: 6,
                type: 1,
                id: "TNK099",
                name: "Logistiknätverk och transporter",
                desc: "Målsättningen för kursen är att studenterna skall få en djup förståelse för hur logistiksystem kan modelleras och analyseras utifrån ett nätverksperspektiv. Speciellt diskuteras transporternas roll som förutsättningar och möjliggörare för konkurrenskraftiga försörjningskedjor och logistiknätverk."},
            {   hp: 6,
                type: 2,
                id: "TEIO87",
                name: "Projektledning",
                desc: "Efter kursen ska studenten kunna tillämpa modeller och teorier om organisation och ledarskap i olika industriella projekt, förklara konsekvenser för individ, grupp och resultat av olika slags ledarskap i projekt. Studenten ska även kunna förstå och förklara hur projektgrupper utvecklas och hur olika faktorer påverkar utvecklingen"},
            {   hp: 6,
                type: 2,
                id: "TNK105",
                name: "Tillämpad optimering II",
                desc: "ett verklighetsbaserat optimeringsproblem, från problemdefinition - via val av modell och metod - till implementering samt experiment och analys."},
            {   hp: 6,
                type: 2,
                id: "TNK104",
                name: "Tillämpad optimering I",
                desc: "Syftet med kursen är att ge kunskap om tillämpning av optimeringslära, med fokus på att tillämpa teorier och metoder i kombinatorisk optimering för att modellera och lösa optimeringsproblem inom transport- och kommunikationsområdet. Kursen syftar även till att ge praktisk färdighet i att sätt upp optimeringsmodeller och använda optimeringsmetoder."},
            {   hp: 6,
                type: 2,
                id: "TNK106",
                name: "Positioneringssystem",
                desc: "Det övergripande målet är att ge såväl teoretisk som praktisk kunskap i olika positioneringstekniker. Detta inkluderar att identifiera de vanligaste positioneringssystemen och deras viktigaste egenskaper samt att kunna tillämpa olika positioneringsmetoder för att uppskatta positionen för ett mål"},
            {   hp: 6,
                type: 2,
                id: "TND012",
                name: "Programmering grk",
                desc: "Kursen skall ge grundläggande kunskaper om hur man konstruerar program i ett högnivåspråk, C++."},
            {   hp: 6,
                type: 1,
                id: "TNK040",
                name: "Telekommunikationssystem",
                desc: "Kursen syftar till att ge förståelse för grundläggande funktioner och begrepp inom digital kommunikation. Studenten ska efter kursen bland annat kunna identifiera de vanligaste komponenterna och funktionerna i ett kommunikationssystem samt Jämföra och förklara användningsområden för olika typer av kommunikationssystem."},
            {   hp: 6,
                type: 1,
                id: "TNK093",
                name: "Mobil kommunikation",
                desc: "Kursen syftar till att ge kunskap inom mobil kommunikation, särskilt för olika systemegenskaper och deras inverkan på prestanda för trådlösa nätverk. Mobiliteten ställer höga krav på kommunikationssystemet och dessa krav tillsammans med möjliga lösningar är en viktig del av kursen."},
            {   hp: 16,
                type: 1,
                id: "TNK111",
                name: "Kommunikation och transport - teknikprojekt",
                desc: "Kandidatrapport. Kursen genomförs för att möjliggöra att studenter kan ta ut en teknisk kandidatexamen."},

            {   hp: 6,
                type: 1,
                id: "TNSL05",
                name: "Optimering, modellering och planering",
                desc: "Kursen skall ge kunskaper i optimeringslära, och speciellt optimering av linjära problem, problem med nätverksstruktur samt heltalsproblem. Speciellt vikt läggs på analys av modeller med koppling till planering av logistiktjänster" },

        ];

            $scope.sort = function(field){
                $scope.sort.field = field;
                $scope.sort.order = !$scope.sort.order;
            };

            $scope.sort.field = 'name';
            $scope.sort.order = false;
            }

        return {
            templateUrl: "/Portfolio/Directives/Courses/coursesDirective.html",
            restrict: 'E',
            link: link
        };
    }])
})();
